name: travel_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  http: ^0.13.4
  provider: ^6.0.3
  intl: ^0.18.1
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.0.6
  flutter_stripe: ^3.0.0
  fl_chart: ^0.40.0
  flutter_localizations:
    sdk: flutter
  badges: ^2.0.2
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gallery-1.jpg
    - assets/gallery-2.jpg
    - assets/gallery-3.jpg
    - assets/gallery-4.jpg
    - assets/gallery-5.jpg
    - assets/hero-banner.jpg
    - assets/popular-1.jpg
    - assets/popular-2.jpg
    - assets/popular-3.jpg
    - assets/package-1.jpg
    - assets/package-2.jpg
    - assets/package-3.jpg
    - assets/profile_pic.jpg
    - assets/virtual_tour.jpg
